Update macos-build.yml

diff --git a/.github/workflows/macos-build.yml b/.github/workflows/macos-build.yml
--- a/.github/workflows/macos-build.yml
+++ b/.github/workflows/macos-build.yml
@@ -36,10 +36,15 @@ jobs:
         run: |
           echo "Instalando Flutter 3.22.3"
           if [ ! -d "/opt/flutter" ]; then
-            echo "Descargando Flutter SDK..." 
-            curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.22.3-stable.tar.xz
-            tar xf flutter_macos_3.22.3-stable.tar.xz
-            mv flutter /opt/flutter
+            echo "Descargando Flutter SDK..."
+            curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.22.3-stable.zip
+            if [ $? -eq 0 ]; then
+              echo "Descarga exitosa, descomprimiendo archivo..."
+              unzip flutter_macos_3.22.3-stable.zip -d /opt
+            else
+              echo "Error en la descarga del archivo"
+              exit 1
+            fi
           fi
 
       # Agregar Flutter al PATH
